Repository youRoom-ISPP/youRoom, pull requests merged in 2021-04, with the labels that each got.

#76 DP: Las publicaciones solo son destacadas por un día - #71
  youroom/publicacion/admin.py
  youroom/ranking/admin.py
  youroom/timeline/views.py
Labels: backend

#78 Resuelve incidencia de ajustes en vista de perfil usuario-#73
  youroom/static/css/custom.css
  youroom/templates/perfil/perfil.html
  youroom/templates/usuario/login.html
Labels: frontend, incidencia

#79 VP: Petición desde la vista de timeline - #40
  youroom/ranking/tests.py
  youroom/ranking/views.py
  youroom/static/css/rating.css
  youroom/static/js/valoracion.js
  youroom/templates/base/base.html
  youroom/templates/timeline/timeline.html
  youroom/timeline/tests_view.py
  youroom/timeline/views.py
Labels: frontend

#77 Lp: Configuración para el almacenamiento de imágenes en AWS s3 #36
  requirements.txt
  youroom/publicacion/tests_views.py
  youroom/youroom/settings.py
Labels: backend, incidencia

#74 Añadir backend de listar ranking-#37
  youroom/ranking/tests.py
  youroom/ranking/views.py
Labels: backend

#80 RP: Limitar cantidad de enlaces-#70
  youroom/publicacion/views.py
  youroom/static/favicon.ico
  youroom/static/js/publicacion.js
  youroom/templates/base/base.html
  youroom/templates/publicacion/modaletiquetas.html
  youroom/templates/publicacion/modalinfo.html
  youroom/templates/publicacion/modalpublicacion.html
  youroom/templates/publicacion/publicacion.html
  youroom/usuario/models.py
Labels: frontend

#81 Correcta visualización del ranking - #75
  youroom/static/css/custom.css
  youroom/templates/ranking/ranking.html
  youroom/templates/timeline/timeline.html
Labels: frontend, incidencia

#85 Implementar frontend destacar de publicaciones-#38
  youroom/perfil/views.py
  youroom/static/css/custom.css
  youroom/static/js/perfil.js
  youroom/templates/base/base.html
  youroom/templates/perfil/destacado.html
  youroom/templates/perfil/perfil.html
  youroom/templates/timeline/timeline.html
Labels: frontend

#84 Creación de la vista de error - #83
  youroom/static/css/custom.css
  youroom/static/css/error.css
  youroom/templates/base/error.html
  youroom/templates/usuario/login.html
Labels: frontend

#87 Solución a la incidencia-#86
  youroom/ranking/views.py
Labels: backend, incidencia

#89 Se ajusta el ancho de visor de imagen-#88
  youroom/static/css/custom.css
  youroom/static/js/publicacion.js
  youroom/templates/perfil/perfil.html
  youroom/templates/publicacion/modalinfo.html
  youroom/templates/timeline/timeline.html
  youroom/templates/usuario/login.html
Labels: frontend, incidencia

#90 Captar posibles errores-#82
  youroom/perfil/views.py
  youroom/publicacion/views.py
  youroom/ranking/views.py
  youroom/timeline/views.py
  youroom/usuario/migrations/0001_initial.py
  youroom/usuario/models.py
Labels: backend

#92 RP: Soluciona imposibilidad de seguir etiquetando-#91
  youroom/static/js/publicacion.js
Labels: frontend, incidencia

#96 Configuración para despliegue en Heroku-#95
  Procfile
  requirements.txt
  youroom/youroom/settings.py
Labels: incidencia

#114 Permitir borrado imagen en la app desplegada-#113
  youroom/publicacion/models.py
Labels: backend, incidencia

#111 Realizado registro de usuarios y tests-#99
  youroom/templates/usuario/registro.html
  youroom/timeline/views.py
  youroom/usuario/forms.py
  youroom/usuario/tests.py
  youroom/usuario/urls.py
  youroom/usuario/views.py
Labels: backend

#118 Resolución de fallos de interfaz-#117
  youroom/static/js/publicacion.js
  youroom/templates/base/base.html
  youroom/templates/perfil/perfil.html
  youroom/templates/publicacion/modalpublicacion.html
Labels: frontend, incidencia

#115 CP: Implementar pago de suscripciones de stripe-#110
  requirements.txt
  youroom/templates/tienda/charge.html
  youroom/templates/tienda/fail.html
  youroom/templates/tienda/home.html
  youroom/tienda/admin.py
  youroom/tienda/migrations/0001_initial.py
  youroom/tienda/models.py
  youroom/tienda/urls.py
  youroom/tienda/views.py
  youroom/youroom/settings.py
Labels: backend

#112 Creación de la vista de registro
  youroom/static/css/custom.css
  youroom/static/css/login.css
  youroom/static/js/registro.js
  youroom/templates/usuario/login.html
  youroom/templates/usuario/registro.html
  youroom/usuario/forms.py
  youroom/usuario/views.py
Labels: frontend

#121 Añadido la posibilidad de realizar el registro en la aplicación.
  requirements.txt
  youroom/publicacion/models.py
  youroom/static/css/custom.css
  youroom/static/css/login.css
  youroom/static/js/publicacion.js
  youroom/static/js/registro.js
  youroom/templates/base/base.html
  youroom/templates/perfil/perfil.html
  youroom/templates/publicacion/modalpublicacion.html
  youroom/templates/tienda/charge.html
  youroom/templates/tienda/fail.html
  youroom/templates/tienda/home.html
  youroom/templates/usuario/login.html
  youroom/templates/usuario/registro.html
  youroom/tienda/__init__.py
  youroom/tienda/admin.py
  youroom/tienda/apps.py
  youroom/tienda/migrations/0001_initial.py
  youroom/tienda/migrations/__init__.py
  youroom/tienda/models.py
  youroom/tienda/tests.py
  youroom/tienda/urls.py
  youroom/tienda/views.py
  youroom/timeline/views.py
  youroom/usuario/forms.py
  youroom/usuario/tests.py
  youroom/usuario/urls.py
  youroom/usuario/views.py
  youroom/youroom/settings.py
  youroom/youroom/urls.py
Labels: backend, frontend

#119 PC: Implementación de pagos de vida-#109
  youroom/products.json
  youroom/publicacion/migrations/0001_initial.py
  youroom/ranking/migrations/0001_initial.py
  youroom/tienda/admin.py
  youroom/tienda/migrations/0001_initial.py
  youroom/tienda/models.py
  youroom/tienda/urls.py
  youroom/tienda/views.py
  youroom/usuario/migrations/0001_initial.py
  youroom/usuario/models.py
Labels: backend

#126 Pc #125
  youroom/templates/tienda/charge.html
  youroom/tienda/tests_views.py
  youroom/tienda/urls.py
  youroom/tienda/views.py
  youroom/usuario/models.py
Labels: backend, incidencia

#128 Añadida funcionalidad de adquirir suscripción desde vista de perfil - #101
  youroom/perfil/test_view.py
  youroom/perfil/views.py
  youroom/publicacion/tests_views.py
  youroom/ranking/tests.py
  youroom/static/css/custom.css
  youroom/static/js/perfil.js
  youroom/templates/base/base.html
  youroom/templates/base/error.html
  youroom/templates/perfil/modalcancelarsuscripcion.html
  youroom/templates/perfil/modaldestacado.html
  youroom/templates/perfil/perfil.html
  youroom/templates/tienda/fail.html
  youroom/tienda/urls.py
  youroom/tienda/views.py
  youroom/timeline/tests_view.py
Labels: frontend

#129 Configurar proceso de recarga de vidas-#116
  requirements.txt
  youroom/usuario/apps.py
  youroom/usuario/cron.py
  youroom/usuario/scheduler/__init__.py
  youroom/usuario/scheduler/scheduler.py
  youroom/usuario/views.py
  youroom/youroom/settings.py
Labels: backend

#131 Implementar vista de tienda - #124
  youroom/perfil/test_view.py
  youroom/perfil/views.py
  youroom/products.json
  youroom/publicacion/tests_views.py
  youroom/ranking/tests.py
  youroom/static/css/custom.css
  youroom/static/images/keys-2.png
  youroom/static/images/keys-3.png
  youroom/static/images/keys-4.png
  youroom/static/images/keys-5.png
  youroom/static/js/perfil.js
  youroom/static/js/tienda.js
  youroom/templates/base/base.html
  youroom/templates/perfil/modal_destacado.html
  youroom/templates/perfil/modal_suscripcion.html
  youroom/templates/perfil/perfil.html
  youroom/templates/tienda/cancelar_suscripcion.html
  youroom/templates/tienda/home.html
  youroom/templates/tienda/tienda.html
  youroom/tienda/models.py
  youroom/tienda/tests_views.py
  youroom/tienda/urls.py
  youroom/tienda/views.py
  youroom/timeline/tests_view.py
Labels: frontend

#130 Configurar cancelación de suscripción-#123
  youroom/usuario/apps.py
  youroom/usuario/scheduler/scheduler.py
  youroom/usuario/views.py
Labels: backend

#135 Pruebas de interfaz para suscripción - #122
  .travis.yml
  youroom/tienda/tests_interface.py
  youroom/tienda/tests_views.py
Labels: backend, frontend, testing

#134 Comprobación de contraseña - #133
  youroom/static/js/registro.js
  youroom/templates/usuario/registro.html
Labels: frontend, incidencia

#139 Corregida navegación a tienda - #138
  youroom/templates/perfil/modal_destacado.html
  youroom/templates/publicacion/modaletiquetas.html
  youroom/templates/publicacion/modalinfo.html
  youroom/templates/usuario/registro.html
Labels: frontend

#140 LU: Listar y mostrar usuarios #127
  youroom/templates/usuario/usuario.html
  youroom/templates/usuario/usuarios.html
  youroom/usuario/serializers.py
  youroom/usuario/tests.py
  youroom/usuario/urls.py
  youroom/usuario/views.py
Labels: backend

#142 Cambio de nombre de los puntos-#141
  youroom/templates/perfil/modal_destacado.html
  youroom/templates/perfil/perfil.html
  youroom/templates/timeline/timeline.html
Labels: frontend

#136 Listado y búsqueda de usuarios-#132
  youroom/static/css/custom.css
  youroom/static/css/usuarios.css
  youroom/static/js/usuarios.js
  youroom/templates/base/base.html
  youroom/templates/perfil/perfil.html
  youroom/templates/ranking/ranking.html
  youroom/templates/timeline/timeline.html
  youroom/templates/usuario/usuario.html
  youroom/templates/usuario/usuarios.html
  youroom/usuario/views.py
Labels: frontend

#143 Añadido las peticiones de los usuarios piloto
  youroom/static/css/custom.css
  youroom/static/css/usuarios.css
  youroom/static/js/usuarios.js
  youroom/templates/base/base.html
  youroom/templates/perfil/modal_destacado.html
  youroom/templates/perfil/perfil.html
  youroom/templates/ranking/ranking.html
  youroom/templates/timeline/timeline.html
  youroom/templates/usuario/usuario.html
  youroom/templates/usuario/usuarios.html
  youroom/usuario/serializers.py
  youroom/usuario/tests.py
  youroom/usuario/urls.py
  youroom/usuario/views.py
Labels: backend, frontend

#147 Inclusión de la política de datos-#145
  youroom/templates/base/base.html
  youroom/templates/rgpd/datos.html
  youroom/usuario/urls.py
  youroom/usuario/views.py
Labels: frontend

#148 AU-Requiere conformidad con política de datos en registro-#146
  youroom/templates/perfil/perfil.html
  youroom/templates/rgpd/datos.html
  youroom/templates/rgpd/rgpd.html
  youroom/templates/usuario/registro.html
Labels: frontend

#155 Añadidas las políticas de datos a la aplicación
  youroom/templates/base/base.html
  youroom/templates/perfil/perfil.html
  youroom/templates/rgpd/datos.html
  youroom/templates/rgpd/rgpd.html
  youroom/templates/usuario/registro.html
  youroom/usuario/urls.py
  youroom/usuario/views.py
Labels: frontend

#154 Mejora en las métricas obtenidas de Codacy-#149
  youroom/perfil/admin.py
  youroom/perfil/models.py
  youroom/perfil/test_view.py
  youroom/perfil/views.py
  youroom/publicacion/enum.py
  youroom/publicacion/tests_views.py
  youroom/publicacion/views.py
  youroom/ranking/admin.py
  youroom/ranking/forms.py
  youroom/ranking/models.py
  youroom/ranking/tests.py
  youroom/ranking/tests_views.py
  youroom/ranking/views.py
  youroom/static/css/custom.css
  youroom/static/css/error.css
  youroom/static/css/login.css
  youroom/static/css/ranking.css
  youroom/static/css/rating.css
  youroom/static/css/usuarios.css
  youroom/static/js/perfil.js
  youroom/static/js/publicacion.js
  youroom/static/js/registro.js
  youroom/static/js/tienda.js
  youroom/static/js/usuarios.js
  youroom/static/js/valoracion.js
  youroom/tienda/models.py
  youroom/tienda/tests.py
  youroom/tienda/tests_interface.py
  youroom/tienda/tests_views.py
  youroom/tienda/views.py
  youroom/timeline/admin.py
  youroom/timeline/models.py
  youroom/timeline/tests_view.py
  youroom/timeline/urls.py
  youroom/timeline/views.py
  youroom/usuario/admin.py
  youroom/usuario/apps.py
  youroom/usuario/forms.py
  youroom/usuario/tests.py
  youroom/usuario/views.py
  youroom/youroom/base_tests.py
Labels: backend, frontend

#157 Mejora en las métricas de Codacy
  youroom/perfil/admin.py
  youroom/perfil/models.py
  youroom/perfil/test_view.py
  youroom/perfil/views.py
  youroom/publicacion/enum.py
  youroom/publicacion/tests_views.py
  youroom/publicacion/views.py
  youroom/ranking/admin.py
  youroom/ranking/forms.py
  youroom/ranking/models.py
  youroom/ranking/tests.py
  youroom/ranking/tests_views.py
  youroom/ranking/views.py
  youroom/static/css/custom.css
  youroom/static/css/error.css
  youroom/static/css/login.css
  youroom/static/css/ranking.css
  youroom/static/css/rating.css
  youroom/static/css/usuarios.css
  youroom/static/js/perfil.js
  youroom/static/js/publicacion.js
  youroom/static/js/registro.js
  youroom/static/js/tienda.js
  youroom/static/js/usuarios.js
  youroom/static/js/valoracion.js
  youroom/tienda/models.py
  youroom/tienda/tests.py
  youroom/tienda/tests_interface.py
  youroom/tienda/tests_views.py
  youroom/tienda/views.py
  youroom/timeline/admin.py
  youroom/timeline/models.py
  youroom/timeline/tests_view.py
  youroom/timeline/urls.py
  youroom/timeline/views.py
  youroom/usuario/admin.py
  youroom/usuario/apps.py
  youroom/usuario/forms.py
  youroom/usuario/tests.py
  youroom/usuario/views.py
  youroom/youroom/base_tests.py
Labels: backend, frontend

#158 Realizado backend comentarios en publicaciones#150
  youroom/publicacion/forms.py
  youroom/publicacion/migrations/0001_initial.py
  youroom/publicacion/models.py
  youroom/publicacion/tests_views.py
  youroom/publicacion/urls.py
  youroom/publicacion/views.py
  youroom/ranking/migrations/0001_initial.py
  youroom/templates/publicacion/mostrar.html
  youroom/tienda/migrations/0001_initial.py
  youroom/timeline/views.py
  youroom/usuario/migrations/0001_initial.py
  youroom/usuario/views.py
Labels: backend

#159 Vistas y lógica de comentarios - #156
  youroom/publicacion/admin.py
  youroom/publicacion/models.py
  youroom/publicacion/tests_views.py
  youroom/publicacion/views.py
  youroom/static/css/custom.css
  youroom/static/css/usuarios.css
  youroom/static/js/comentar.js
  youroom/templates/base/base.html
  youroom/templates/perfil/perfil.html
  youroom/templates/publicacion/mostrar.html
  youroom/templates/timeline/timeline.html
  youroom/templates/usuario/usuario.html
  youroom/timeline/views.py
Labels: frontend

#162 Arreglada la incidencia con los comentarios-#160
  youroom/publicacion/views.py
Labels: backend, incidencia

#164 Arreglada incidencia de ver puntuacion-#163
  youroom/publicacion/views.py
  youroom/templates/publicacion/mostrar.html
Labels: backend, frontend, incidencia

#165 Nueva funcionalidad de comentarios implementada
  youroom/publicacion/admin.py
  youroom/publicacion/forms.py
  youroom/publicacion/migrations/0001_initial.py
  youroom/publicacion/models.py
  youroom/publicacion/tests_views.py
  youroom/publicacion/urls.py
  youroom/publicacion/views.py
  youroom/ranking/migrations/0001_initial.py
  youroom/static/css/custom.css
  youroom/static/css/usuarios.css
  youroom/static/js/comentar.js
  youroom/templates/base/base.html
  youroom/templates/perfil/perfil.html
  youroom/templates/publicacion/mostrar.html
  youroom/templates/timeline/timeline.html
  youroom/templates/usuario/usuario.html
  youroom/tienda/migrations/0001_initial.py
  youroom/timeline/views.py
  youroom/usuario/migrations/0001_initial.py
  youroom/usuario/views.py
Labels: backend, frontend

#161 Edición de perfil - #151
  youroom/perfil/forms.py
  youroom/perfil/test_view.py
  youroom/perfil/urls.py
  youroom/perfil/views.py
  youroom/publicacion/migrations/0001_initial.py
  youroom/ranking/migrations/0001_initial.py
  youroom/templates/perfil/editar_perfil.html
  youroom/tienda/migrations/0001_initial.py
  youroom/usuario/migrations/0001_initial.py
  youroom/usuario/models.py
  youroom/youroom/base_tests.py
Labels: backend, enhancement

#166 Crear vista de edición del perfil y añadir las imágenes de los usuarios en sus perfiles #152
  youroom/perfil/views.py
  youroom/static/css/croppie.css
  youroom/static/css/custom.css
  youroom/static/images/default_profile.png
  youroom/static/js/croppie.min.js
  youroom/static/js/publicacion.js
  youroom/static/js/recorte_imagen.js
  youroom/static/js/registro.js
  youroom/templates/base/base.html
  youroom/templates/perfil/editar_perfil.html
  youroom/templates/perfil/modal_recortar_foto_perfil.html
  youroom/templates/perfil/perfil.html
  youroom/templates/publicacion/publicacion.html
  youroom/templates/timeline/timeline.html
  youroom/templates/usuario/registro.html
  youroom/templates/usuario/usuario.html
  youroom/usuario/forms.py
  youroom/usuario/models.py
Labels: frontend

#167 Nueva funcionalidad de edición del perfil implementada
  youroom/perfil/forms.py
  youroom/perfil/test_view.py
  youroom/perfil/urls.py
  youroom/perfil/views.py
  youroom/publicacion/migrations/0001_initial.py
  youroom/ranking/migrations/0001_initial.py
  youroom/static/css/croppie.css
  youroom/static/css/custom.css
  youroom/static/images/default_profile.png
  youroom/static/js/croppie.min.js
  youroom/static/js/publicacion.js
  youroom/static/js/recorte_imagen.js
  youroom/static/js/registro.js
  youroom/templates/base/base.html
  youroom/templates/perfil/editar_perfil.html
  youroom/templates/perfil/modal_recortar_foto_perfil.html
  youroom/templates/perfil/perfil.html
  youroom/templates/publicacion/publicacion.html
  youroom/templates/timeline/timeline.html
  youroom/templates/usuario/registro.html
  youroom/templates/usuario/usuario.html
  youroom/tienda/migrations/0001_initial.py
  youroom/usuario/forms.py
  youroom/usuario/migrations/0001_initial.py
  youroom/usuario/models.py
  youroom/youroom/base_tests.py
Labels: backend, frontend

#169 Resolución de incidencias varias - #153
  youroom/perfil/test_view.py
  youroom/publicacion/views.py
  youroom/static/css/croppie.css
  youroom/static/css/custom.css
  youroom/static/js/recorte_imagen.js
  youroom/templates/base/base.html
  youroom/templates/perfil/perfil.html
  youroom/templates/publicacion/mostrar.html
  youroom/templates/ranking/ranking.html
  youroom/templates/tienda/tienda.html
  youroom/templates/timeline/timeline.html
  youroom/templates/usuario/usuario.html
  youroom/usuario/forms.py
Labels: frontend, incidencia

#171 Implementación de edición de publicación-#170
  youroom/perfil/test_view.py
  youroom/publicacion/enum.py
  youroom/publicacion/models.py
  youroom/publicacion/tests_views.py
  youroom/publicacion/urls.py
  youroom/publicacion/views.py
  youroom/static/css/croppie.css
  youroom/templates/publicacion/publicacion_editar.html
  youroom/timeline/tests_view.py
Labels: backend

#172 Añadida vista de edición de publicación - #168
  youroom/publicacion/enum.py
  youroom/publicacion/views.py
  youroom/static/css/custom.css
  youroom/templates/perfil/perfil.html
  youroom/templates/publicacion/modalpublicacion.html
  youroom/templates/publicacion/publicacion_editar.html
  youroom/templates/timeline/timeline.html
Labels: frontend

#176 Nueva funcionalidad de edición de la publicación implementada
  youroom/perfil/test_view.py
  youroom/publicacion/enum.py
  youroom/publicacion/models.py
  youroom/publicacion/tests_views.py
  youroom/publicacion/urls.py
  youroom/publicacion/views.py
  youroom/static/css/croppie.css
  youroom/static/css/custom.css
  youroom/static/js/recorte_imagen.js
  youroom/templates/base/base.html
  youroom/templates/perfil/perfil.html
  youroom/templates/publicacion/modalpublicacion.html
  youroom/templates/publicacion/mostrar.html
  youroom/templates/publicacion/publicacion_editar.html
  youroom/templates/ranking/ranking.html
  youroom/templates/tienda/tienda.html
  youroom/templates/timeline/timeline.html
  youroom/templates/usuario/usuario.html
  youroom/timeline/tests_view.py
  youroom/usuario/forms.py
Labels: backend, frontend

#173 Actualizar puntos del ranking cuando se elimina una publicación #144
  youroom/publicacion/enum.py
  youroom/publicacion/migrations/0001_initial.py
  youroom/publicacion/models.py
  youroom/ranking/migrations/0001_initial.py
  youroom/templates/perfil/perfil.html
  youroom/tienda/migrations/0001_initial.py
  youroom/usuario/migrations/0001_initial.py
Labels: backend, incidencia
