Repository youRoom-ISPP/youRoom, pull requests merged in 2021-05, with the labels that each got.

#178 Eliminar usuarios con 0 estrellas de ranking-#177
  youroom/ranking/tests_views.py
  youroom/ranking/views.py
  youroom/templates/ranking/ranking.html
Labels: incidencia

#180 Resueltas las incidencias - #179
  youroom/static/css/custom.css
  youroom/templates/perfil/perfil.html
  youroom/templates/publicacion/mostrar.html
  youroom/templates/publicacion/publicacion_editar.html
  youroom/templates/timeline/timeline.html
  youroom/templates/usuario/usuario.html
Labels: frontend, incidencia

#181 Resuelto numerosas incidencias
  youroom/publicacion/enum.py
  youroom/publicacion/migrations/0001_initial.py
  youroom/publicacion/models.py
  youroom/ranking/migrations/0001_initial.py
  youroom/ranking/tests_views.py
  youroom/ranking/views.py
  youroom/static/css/custom.css
  youroom/templates/perfil/perfil.html
  youroom/templates/publicacion/mostrar.html
  youroom/templates/publicacion/publicacion_editar.html
  youroom/templates/ranking/ranking.html
  youroom/templates/rgpd/rgpd.html
  youroom/templates/timeline/timeline.html
  youroom/templates/usuario/usuario.html
  youroom/tienda/migrations/0001_initial.py
  youroom/usuario/migrations/0001_initial.py
Labels: backend, frontend

#189 LR: Modificación del ranking para que sea semanal-#184
  youroom/ranking/tests_views.py
  youroom/ranking/views.py
  youroom/templates/ranking/ranking.html
  youroom/usuario/migrations/0001_initial.py
  youroom/usuario/models.py
Labels: backend

#190 Realizada paginación-#187
  youroom/perfil/views.py
  youroom/static/css/custom.css
  youroom/static/js/infinite-scroll.js
  youroom/static/js/infinite.min.js
  youroom/static/js/jquery.waypoints.min.js
  youroom/templates/base/base.html
  youroom/templates/perfil/perfil.html
  youroom/templates/timeline/timeline.html
  youroom/templates/usuario/usuario.html
  youroom/timeline/views.py
  youroom/usuario/views.py
Labels: backend, frontend

#191 LP: Ordenar publicaciones por valoración - #185
  youroom/static/css/custom.css
  youroom/templates/timeline/timeline.html
  youroom/timeline/tests_view.py
  youroom/timeline/urls.py
  youroom/timeline/views.py
Labels: backend, frontend

#193 Nueva funcionalidad de listado de más valoradas implementada
  youroom/perfil/views.py
  youroom/ranking/tests_views.py
  youroom/ranking/views.py
  youroom/static/css/custom.css
  youroom/static/js/infinite-scroll.js
  youroom/static/js/infinite.min.js
  youroom/static/js/jquery.waypoints.min.js
  youroom/templates/base/base.html
  youroom/templates/perfil/perfil.html
  youroom/templates/ranking/ranking.html
  youroom/templates/timeline/timeline.html
  youroom/templates/usuario/usuario.html
  youroom/timeline/tests_view.py
  youroom/timeline/urls.py
  youroom/timeline/views.py
  youroom/usuario/migrations/0001_initial.py
  youroom/usuario/models.py
  youroom/usuario/views.py
Labels: backend, frontend

#192 Resolver las issues #182 #183 #186
  youroom/ranking/views.py
  youroom/static/css/custom.css
  youroom/static/js/publicacion.js
  youroom/static/js/valoracion.js
  youroom/templates/base/base.html
  youroom/templates/guia/guia.html
  youroom/templates/perfil/modal_destacado.html
  youroom/templates/perfil/perfil.html
  youroom/templates/ranking/ranking.html
  youroom/templates/timeline/timeline.html
  youroom/templates/usuario/usuario.html
  youroom/timeline/tests_view.py
  youroom/timeline/views.py
  youroom/usuario/apps.py
  youroom/usuario/scheduler/scheduler.py
  youroom/usuario/urls.py
  youroom/usuario/views.py
Labels: backend, frontend

#194 Añadido corrección a la incidencia-#188
  youroom/timeline/views.py
Labels: incidencia

#195 Resolución de incidencias y mejoras
  youroom/ranking/views.py
  youroom/static/css/custom.css
  youroom/static/js/publicacion.js
  youroom/static/js/valoracion.js
  youroom/templates/base/base.html
  youroom/templates/guia/guia.html
  youroom/templates/perfil/modal_destacado.html
  youroom/templates/perfil/perfil.html
  youroom/templates/ranking/ranking.html
  youroom/templates/timeline/timeline.html
  youroom/templates/usuario/usuario.html
  youroom/timeline/tests_view.py
  youroom/timeline/views.py
  youroom/usuario/apps.py
  youroom/usuario/scheduler/scheduler.py
  youroom/usuario/urls.py
  youroom/usuario/views.py
Labels: backend, frontend
