Repository youRoom-ISPP/youRoom, pull requests merged in 2021-03, with the labels that each got.

#21 Añade diseño y estilos base-#13
  youroom/static/css/custom.css
  youroom/templates/base/base.html
  youroom/templates/usuario/login.html
Labels: frontend

#24 AU: Vista de login
  youroom/static/css/custom.css
  youroom/templates/base/base.html
  youroom/templates/usuario/login.html
  youroom/usuario/migrations/0001_initial.py
Labels: frontend

#26 RP: Creación formulario publicación
  requirements.txt
  youroom/publicacion/enum.py
  youroom/publicacion/forms.py
  youroom/publicacion/migrations/0001_initial.py
  youroom/publicacion/models.py
  youroom/publicacion/tests.py
  youroom/publicacion/tests_views.py
  youroom/publicacion/urls.py
  youroom/publicacion/views.py
  youroom/templates/publicacion/subir_imagen.html
  youroom/youroom/settings.py
  youroom/youroom/urls.py
Labels: backend

#27 Caso de uso core crear publicación-#19
  .gitignore
  youroom/publicacion/admin.py
  youroom/publicacion/enum.py
  youroom/publicacion/forms.py
  youroom/publicacion/views.py
  youroom/static/css/custom.css
  youroom/static/js/publicacion.js
  youroom/templates/base/base.html
  youroom/templates/publicacion/publicacion.html
  youroom/templates/publicacion/subir_imagen.html
  youroom/youroom/urls.py
Labels: backend, frontend

#28 Realizar etiquetado de imagenes-#12
  youroom/publicacion/admin.py
  youroom/publicacion/forms.py
  youroom/publicacion/migrations/0001_initial.py
  youroom/publicacion/models.py
  youroom/publicacion/views.py
  youroom/static/js/publicacion.js
  youroom/templates/base/base.html
  youroom/templates/publicacion/publicacion.html
Labels: backend, frontend

#29 Añadir listado de publicaciones-#10
  youroom/timeline/views.py
Labels: backend

#30 Integración con el backend para listar publicaciones #16
  youroom/static/css/custom.css
  youroom/static/css/rating.css
  youroom/static/images/logo-xl.png
  youroom/templates/base/base.html
  youroom/templates/timeline/timeline.html
  youroom/timeline/urls.py
  youroom/youroom/urls.py
Labels: frontend

#31 Integración con lista de publicaciones #14
  youroom/perfil/urls.py
  youroom/perfil/views.py
  youroom/templates/perfil/perfil.html
  youroom/youroom/urls.py
Labels: frontend

#44 Completada la vista de ranking de usuarios - #17
  youroom/ranking/urls.py
  youroom/ranking/views.py
  youroom/static/css/custom.css
  youroom/static/css/ranking.css
  youroom/templates/ranking/ranking.html
  youroom/youroom/urls.py
Labels: frontend

#48 LP: Listar publicaciones-#10
  youroom/templates/timeline/timeline.html
  youroom/timeline/tests.py
  youroom/timeline/tests_view.py
  youroom/timeline/urls.py
  youroom/timeline/views.py
Labels: backend

#52 Resolución de incidencia en develop-#51
  youroom/templates/base/base.html
  youroom/templates/timeline/timeline.html
Labels: incidencia

#53 RP: Redirigir al perfil cuando se publique-#34
  youroom/publicacion/tests_views.py
  youroom/publicacion/views.py
Labels: backend, incidencia

#50 VP: Realizar una valoración #41
  youroom/publicacion/migrations/0001_initial.py
  youroom/ranking/forms.py
  youroom/ranking/migrations/0001_initial.py
  youroom/ranking/models.py
  youroom/ranking/tests.py
  youroom/ranking/urls.py
  youroom/ranking/views.py
  youroom/templates/timeline/timeline.html
  youroom/timeline/urls.py
  youroom/timeline/views.py
  youroom/usuario/migrations/0001_initial.py
Labels: backend

#57 Resolución de incidencias - #32 #33
  youroom/usuario/views.py
Labels: backend, incidencia

#58 DP: Realizar el destacado-#39
  youroom/publicacion/migrations/0001_initial.py
  youroom/publicacion/models.py
  youroom/publicacion/tests_views.py
  youroom/publicacion/urls.py
  youroom/publicacion/views.py
  youroom/timeline/tests_view.py
Labels: backend

#59 Resolución de incidencia - #35
  youroom/publicacion/models.py
Labels: backend, incidencia

#60 Ajustes de diseño frontend-#54
  youroom/static/css/custom.css
  youroom/templates/base/base.html
  youroom/templates/publicacion/publicacion.html
  youroom/templates/timeline/timeline.html
Labels: frontend

#69 LR: Actualización de modelos - #56
  requirements.txt
  youroom/perfil/test_view.py
  youroom/perfil/views.py
  youroom/publicacion/migrations/0001_initial.py
  youroom/publicacion/models.py
  youroom/publicacion/tests_views.py
  youroom/publicacion/views.py
  youroom/ranking/migrations/0001_initial.py
  youroom/ranking/tests.py
  youroom/ranking/views.py
  youroom/timeline/tests_view.py
  youroom/usuario/cron.py
  youroom/usuario/migrations/0001_initial.py
  youroom/usuario/models.py
  youroom/youroom/settings.py
Labels: backend

#68 PU: Vista de perfil de usuario-#14
  youroom/templates/perfil/perfil.html
Labels: frontend

#72 Web responsive #47
  youroom/static/css/custom.css
  youroom/static/css/ranking.css
  youroom/static/images/smartphones.png
  youroom/templates/base/base.html
  youroom/templates/perfil/perfil.html
  youroom/templates/publicacion/publicacion.html
  youroom/templates/ranking/ranking.html
  youroom/templates/timeline/timeline.html
  youroom/templates/usuario/login.html
Labels: frontend
